### ISSUE TITLE
Question: How to contribute internal level?

### ISSUE THREAD

**Issue by Luxusio** [myjian/mai-tools#47]
as title

**Comment by myjian** [comment]
Hi, since d36c5de164cb874d9680ae17dd7dfbac77c53936, you can contribute internal level by updating https://github.com/myjian/mai-tools/blob/gh-pages/data/chart-levels/version19.json (FESTiVAL)
If you want to contribute to FESTiVAL PLUS internal levels, please create version20.json with same format as version19.json.
